# Generated by Django 6.0.4 on 2026-04-18 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('cpu', models.CharField(max_length=100)),
                ('ram_gb', models.SmallIntegerField()),
                ('storage_gb', models.SmallIntegerField()),
                ('screen_in', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gpu', models.CharField(max_length=100)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('os', models.CharField(max_length=50)),
                ('ram_gb', models.SmallIntegerField()),
                ('storage_gb', models.SmallIntegerField()),
                ('camera_mp', models.SmallIntegerField()),
                ('battery_mah', models.IntegerField()),
            ],
            bases=('products.product',),
        ),
    ]
