# Generated by Django 6.0.2 on 2026-04-20 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name': 'Smartphone', 'verbose_name_plural': 'Smartphones'},
        ),
        migrations.AddField(
            model_name='laptop',
            name='battery_wh',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='laptop',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='network',
            field=models.CharField(choices=[('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=10),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_gb',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_gb',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix (MAD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL source'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_mah',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_mp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='os',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_gb',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage_gb',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='laptop',
            table='tc_laptop',
        ),
        migrations.AlterModelTable(
            name='product',
            table='tc_product',
        ),
        migrations.AlterModelTable(
            name='smartphone',
            table='tc_smartphone',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'db_table': 'tc_userprofile',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'tc_favorite',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
