# Generated by Django 6.0.4 on 2026-05-14 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_laptop_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='release_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Année de sortie'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='release_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Année de sortie'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='NotificationModel',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('notification_type', models.CharField(choices=[('price_drop', 'Baisse de prix'), ('new_product', 'Nouveau produit'), ('comparison', 'Résultat comparaison'), ('restock', 'Produit en stock'), ('system', 'Message système')], default='system', max_length=20)),
                        ('title', models.CharField(max_length=200)),
                        ('message', models.TextField()),
                        ('is_read', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('read_at', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Notification',
                        'verbose_name_plural': 'Notifications',
                        'db_table': 'tc_notification',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],  # table already exists, skip creation
        ),
        migrations.CreateModel(
            name='SavedComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='saved_in_comparisons', to='products.product', verbose_name='Produits comparés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_comparisons', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Comparaison sauvegardée',
                'verbose_name_plural': 'Comparaisons sauvegardées',
                'db_table': 'tc_saved_comparison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix cible (MAD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Alerte prix',
                'verbose_name_plural': 'Alertes prix',
                'db_table': 'tc_price_alert',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'tc_review',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
